#!/usr/bin/python3
# encoding: utf-8
# -*- coding: utf8 -*-
"""
Created by PyCharm.
File:               LinuxBashShellScriptForOps:apiTestWeChatWithWxpy.py
User:               Guodong
Create Date:        2017/3/16
Create Time:        13:44

[把警告/日志发到自己的微信上](https://zhuanlan.zhihu.com/p/25768417)
[微信机器人 / 优雅的微信个人号API / wxpy: 用 Python 玩微信](https://github.com/youfou/wxpy)

Please do NOT edit this file directly unless you know what does it mean

 """
